{
 "title": "Flink Command Center",
 "tags": [
  "flink",
  "pageview",
  "infrastructure"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job_id",
    "label": "Job ID",
    "query": "label_values(flink_jobmanager_job_uptime, job_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Ingestion Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(flink_taskmanager_job_task_operator_numRecordsOut{job_id=\"$job_id\", operator_name=~\"Source.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total Processed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_numRecordsOut{job_id=\"$job_id\", operator_name=~\"Source.*\"})"
    }
   ]
  },
  {
   "title": "Job Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(flink_jobmanager_job_uptime{job_id=\"$job_id\"}/1000) and (time() - timestamp(flink_jobmanager_job_uptime{job_id=\"$job_id\"}) < 60)"
    }
   ]
  },
  {
   "title": "Checkpoints",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_job_totalNumberOfCheckpoints{job_id=\"$job_id\"}"
    }
   ]
  },
  {
   "title": "CP Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_job_lastCheckpointDuration{job_id=\"$job_id\"}"
    }
   ]
  },
  {
   "title": "CP Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_job_lastCheckpointSize{job_id=\"$job_id\"}"
    }
   ]
  },
  {
   "title": "Resource Utilization (CPU)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_CPU_Load",
     "legendFormat": "JobManager CPU"
    },
    {
     "expr": "sum(flink_taskmanager_Status_JVM_CPU_Load)",
     "legendFormat": "TaskManagers CPU"
    }
   ]
  },
  {
   "title": "Memory Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Used",
     "legendFormat": "JobManager Heap Used"
    },
    {
     "expr": "sum(flink_taskmanager_Status_JVM_Memory_Heap_Used)",
     "legendFormat": "TaskManagers Heap Used"
    }
   ]
  }
 ]
}