{
 "title": "Data Generator",
 "tags": [
  "generator",
  "pageview"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Published Events",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pageview_events_published_total"
    }
   ]
  },
  {
   "title": "Publishing Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pageview_events_published_total[1m])"
    }
   ]
  },
  {
   "title": "Publish Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pageview_publish_errors_total" }
   ]
  },
  {
   "title": "Event Publishing Rate (Over Time)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(pageview_events_published_total[1m])",
     "legendFormat": "Publish Rate"
    }
   ]
  }
 ]
}